"""changed column names

Revision ID: 7f78d71c90d7
Revises: b6d2e1760c16
Create Date: 2026-03-16 23:18:34.822273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f78d71c90d7'
down_revision: Union[str, Sequence[str], None] = 'b6d2e1760c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('weather', sa.Column('checked_at', sa.DateTime(), nullable=True))
    op.drop_column('weather', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('weather', 'checked_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
