"""create posts column

Revision ID: b6d2e1760c16
Revises: 
Create Date: 2026-03-16 23:12:41.319981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d2e1760c16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('current_temp', sa.Float(), nullable=False))
    op.add_column('weather', sa.Column('feels_like', sa.Float(), nullable=False))
    op.add_column('weather', sa.Column('minimum_temp', sa.Float(), nullable=False))
    op.add_column('weather', sa.Column('maximum_temp', sa.Float(), nullable=False))
    op.drop_column('weather', 'temperature')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('temperature', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('weather', 'maximum_temp')
    op.drop_column('weather', 'minimum_temp')
    op.drop_column('weather', 'feels_like')
    op.drop_column('weather', 'current_temp')
    # ### end Alembic commands ###
